version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: ibnuqoyyim
    container_name: ibnuqoyyim-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mariadb/server
    container_name: ibnuqoyyim-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:latest
    environment:
        ADMINER_DEFAULT_DB_DRIVER: mysql
        ADMINER_DEFAULT_DB_HOST: localhost
        ADMINER_DEFAULT_DB_NAME: db
        # ADMINER_DESIGN: dracula
        ADMINER_PLUGINS: tables-filter tinymce
    ports:
    - 8001:8080

  nginx:
    image: nginx:alpine
    container_name: ibnuqoyyim-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

networks:
  ibnuqoyyim:
    driver: bridge
